#!/bin/sh
sudo echo " "
echo "Installa yay eseguendo "
echo "pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si"

echo "Git ssh"
echo "ssh-keygen -t ed25519 -C "timothymisso00@gmail.com"
echo " eval "$(ssh-agent -s)"  "
echo "  ssh-add ~/.ssh/id_ed25519 "
echo " cat ~/.ssh/id_ed25519.pub "
echo "Copy/Paste to github"

echo "git config --global user.name "timothymisso988""
echo "git config --global user.email "timothymisso00@gmail.com" "
echo "ssh -T git@github.com""

echo "Per far funzionare Discover"
echo "yay packagekit-qt5"

sudo systemctl start NetworkManager
sudo systemctl enable NetworkManager


sudo systemctl start sshd.service
sudo systemctl enable sshd


sudo systemctl start bluetooth.service
sudo systemctl enable bluetooth.service
exho " "
echo "Installa/timeshift/google/telegram/qbittorrent"
echo "yay timeshift googlechrom"
