#!/bin/sh
sudo echo " "
cd /home
pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si

sudo systemctl start NetworkManager
sudo systemctl enable NetworkManager


sudo systemctl start sshd.service
sudo systemctl enable sshd


sudo systemctl start bluetooth.service
sudo systemctl enable bluetooth.service

yay timeshift
yay google-chrome
