#!/bin/sh
location=$PWD
echo "With this script you can automatically update your ssh keys"
echo "Insert your email"
read email
git config --global user.email $email
echo "Insert your github username"
read username
git config --global user.name $username
echo "Now I am creating the keys..."
#yes |sudo pacman -S openssh
#sudo apt install openssh-server --yes
ssh-keygen -t rsa -b 4096 -C "$email"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
cd ~/.ssh
#yes | sudo pacman -S xclip
#sudo apt-get install xclip --yes
cat ~/.id_rsa.pub
cd /
cd "$location"
read -p "Would you like to clone all of your repositories in a subfolder (y/n)?" choice
case "$choice" in 
  y|Y ) mkdir repositories
cd repositories
	 curl -s https://api.github.com/users/timothy988/repos | grep \"clone_url\" | awk '{print $2}' | sed -e 's/"//g' -e 's/,//g' | xargs -n1 git clone
;;
  n|N ) echo "We are done here!";;
  * ) echo "invalid";;
esac
echo "IMPORTANT NOW COPY THE KEY TO THE GITHUB PAGE THAT I AM OPENING"

read -p "Which browser would you like to use for setting up the keys (chrome firefox chromium) " browser
case "$browser" in
	chrome) echo "Ok you have chosen chrome"
google-chrome-stable https://github.com/settings/keys https://accounts.google.com/signin/v2/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&service=mail&sacu=1&rip=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin > /dev/null 2>&1 | grep -m 1 -o "abc" | grep -o "123"
		echo""
		echo "Would you like to add identity(y/n) ";;
	firefox) firefox --no-sandbox gmail.com github.com/settings/keys
		echo"";;
		chromium)
			chromium gmail.com github.com/settings/keys 
			echo "";;
		esac
echo "DON'T ADD IDENTITIES BEFORE ADDING KEYS!!!"
echo "PRESS YES IF YOU HAVE Copied the keys"
read -p "Would you like to add identity (y/n) " identity
case "$identity" in
	y|Y)echo "Ok i will add your identity"
		ssh -T git@github.com
		echo ""
		echo "Perfetto non devi piu preoccuparti di github!!!";;
	n|N)echo "Ok identity not added";;
	*) echo "Invalid character";;
esac
