#!/bin/sh
sudo apt install build-essential cmake python3-dev --yes
sudo apt-get install npm --yes
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
cd /home/timothy/.vim/plugged/YouCompleteMe
python3 install.py --ts-completer

