name: Test code and embed into README

on: [push]

jobs:
  readme-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: refs/heads/${{ github.head_ref }}
          
      

      - name: embedding readme
        uses: timothy988/Scriptini
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "auto commit for embedding"
          no_change: "No change on Readme."
          silent: false

- name: script run

      run: |

        echo Add other actions to build,

        echo test, and deploy your project.

